### PR TITLE
Flatten package-lock.json and remove unused devDependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
~~Requires #61 and includes #62. If there are any conflicts just CC me to redo the commit :)~~

1328 packages -> 1268 packages.

EDIT: after the last patches 1328 -> 1290 packages

### CODE REVIEW

**Comment by XhmikosR** [comment]
This is an issue that you will hit due again, unfortunately. I have to regenerate package-lock.json from time to time myself in all projects.

**Comment by tancredi** [comment]
Apologies, but could you give me a little more context here?

**Comment by XhmikosR** [comment]
When using dependabot, package-lock.json tends to not be unflattened. It's an old issue I have reported to them, but it could be an issue with npm as well. So, form time to time, one has to regenerate package-lock.json to get the flattened deps.

**Comment by XhmikosR** [comment]
Do note that this only affects the package itself and not its consumers since npm installs the latest versions of the dependencies which adhere to semver.

**Comment by tancredi** [comment]
Pardon again, what do you mean by unflattened and how are you flattening? Just so that I can maintain correctly this in the future and not just do a one-off :)

**Comment by XhmikosR** [comment]
So, package managers like npm and yarn, try to flatten the dependencies whenever they can. If they didn't, every package would include each of their dependencies going down the tree. Imagine having 800 lodash instances for example.

Now, there is this issue (which I don't know for sure who's to blame) when one is using dependabot with npm, the dependencies are not flattened, thus we end up with a suboptimal deps tree like here.

Doing this you can replicate this in the future:

```bash
rm -r ./node_modules/
rm package-lock.json
npm i
```

BTW this will install the latest semver compatible version, and you current dependabot config only updates the lock file and not package.json too. Personally, I always set dependabot to update both files.

**Comment by tancredi** [comment]
Ah okok I was just confused by 'flattening', as in de-duplicating deps. And didn't quite get you were just re-buildibg a fresh package lock with 'npm i'. Sounds good, gonna make sure to keep this on track ;) thanks again for the Christmas PRs!

**Review by tancredi — APPROVED** [review]

**Comment by XhmikosR** [comment]
I added 2 more patches. I'm not familiar with semantic-release, so please confirm that these packages were indeed unused.

I think the changelog one was unused for sure since there's no CHANGELOG.md file in the repo. The git package is what I'm not sure about :)

**Comment by XhmikosR** [comment]
I made another patch: https://github.com/XhmikosR/fantasticon/compare/deps...XhmikosR:rm-lodash

I'll wait until #83 and this PR are merged before I open a new PR since there might be conflicts and also lodash `startsWith` does a few more checks which I'm not familiar enough with the codebase to decide if they are still needed or not.

**Comment by tancredi** [comment]
Flattened after further deps updates 👍

**Pull request closed without merging**
