### PR TITLE
CI improvements

### PR DESCRIPTION
**Pull request by tancredi**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@tancredi there's no matrix.os in lint

**Comment by XhmikosR** [comment]
Also, you could probably remove the cache fallback line `${{ matrix.os }}-node-v${{ env.NODE }}-`

**Comment by tancredi** [comment]
Oopsy - https://github.com/tancredi/fantasticon/pull/112

TBH I'd almost remove fallbacks entirely - i'd expect cache keys to be either correct or not, but it kinda just makes the thing more unreadable in a way. What do you think?

**Comment by XhmikosR** [comment]
I'd say just remove the aforementioned fallback and keep the exact match. Better have a cache miss that cache growing, assuming you it's not a lot slower.

**Comment by tancredi** [comment]
But why that one specifically and not others?

**Comment by XhmikosR** [comment]
The other one is not a fallback. It's needed so that the cache action knows what to restore AFAICT.

**Comment by tancredi** [comment]
Meh - still not totally convinced as I think caching here is far less critical than maintainability and deffo don't see the point in a fallback key (I'd either hit exact key or not hit anything ay all), for the time being just removed that line :)

**Comment by XhmikosR** [comment]
Like I said, the only fallback there is is that line wherever repeated. The other line is needed for caching. If you don't want caching, that's another thing, but it definitely speeds things up.

**Pull request merged**
