### PR TITLE
Support codepoint helper in html generator

### PR DESCRIPTION
**Pull request by jk-clarabridge**
Codepoint in HTML is useful for providing values that can be used in entity codes or CSS `content` property

### CODE REVIEW

**Comment by tancredi** [comment]
Hi @janbiasi - Would it be OK to have the same helper provided in the other generators (e.g. `css`?) would since it would be used in quite a few places I'd like to have that abstracted into a separate module (e.g. `utils/handlebars-helpers`) and have at least a test for `codepoint` method.

So, basically, re-use the `{ helpers: { codepoint: str => str.toString(16) } }` from https://github.com/jk-clarabridge/fantasticon/blob/feat/codepoint-in-html/src/generators/asset-types/css.ts if possible?

**Comment by tancredi** [comment]
(And of course, thank you for contributing 🙏)

**Comment by jk-clarabridge** [comment]
Should be a little more like you requested

**Comment by tancredi** [comment]
Extended and merged in https://github.com/tancredi/fantasticon/pull/80 (where I wanted to use a default helpers object which would be consistent across all templates) - thank you so much and sorry for the wait - will be released soon!

**Pull request merged**
